### ISSUE TITLE
Add-on is using unofficial Manifest V3 support.

### ISSUE THREAD

**Issue by jobisoft** [2AStudios/tb-export2csv#1]
Thunderbird had experimental support for Manifest V3, but it was not intended for production use. We had a warning banner at the top of the documentation:
https://web.archive.org/web/20230323145704/https://webextension-api.thunderbird.net/en/latest-mv3/

With Thunderbird 128, we finalized our Manifest V3 support:
https://webextension-api.thunderbird.net/en/128-esr-mv3/index.html

Your add-on needs changes in order to work with the finalized Manifest V3 support:
* we do not use `MailFolder` as input anymore, but MailFolder.id

**Comment by TokioChef** [comment]
Tested and Pull request merged.  Issue closed
