### ISSUE TITLE
Does not work with Thunderbird 128

### ISSUE THREAD

**Issue by kunalbedi** [2AStudios/tb-export2csv#7]
Does not work with Thunderbird 128

I use this extension and latest thunderbird does not support this plugin anymore.
Is there a chance for an update?

Regards
Kunal

**Comment by TokioChef** [comment]
> Does not work with Thunderbird 128
> 
> I use this extension and latest thunderbird does not support this plugin anymore. Is there a chance for an update?
> 
> Regards Kunal

Absolutely.  We pushed an update to support TB128, just waiting for it to go live.  Thanks for checking though and a ticket should be resolved quickly to get you the update live.  (FYI, code here was updated a couple weeks back).
